import React, { useState } from 'react';

const Mercury = () => {
    const [expanded, setExpanded] = useState(false);

    return (
        <div className="text-sm text-gray-300 space-y-4">
            {/* Real Image of Mercury */}
            <div className="flex justify-center items-center w-full h-full bg-black py-6">
                <div className="relative w-60 h-60 rounded-full overflow-visible">
                    <img
                        src="https://imgs.search.brave.com/MvHi76yLKfHbmLPGJWbvy2WOzU_qNgUhoiATPbGiZjM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDQwNDcy/MjYuanBn"
                        alt="Mercury Real"
                        className="absolute top-0 left-0 w-full h-full object-cover rounded-full"
                    />
                </div>
            </div>

            {/* Basic Info */}
            <div>
                <h3 className="text-xl font-semibold text-white">Mercury</h3>
                <p className="mt-1 text-gray-400">
                    Mercury is the closest planet to the Sun and the smallest in our solar system, with an extremely thin atmosphere.
                </p>
            </div>

            {/* Key Facts */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 border-t border-gray-700 pt-4">
                <div>
                    <h4 className="text-white font-medium mb-1">Size & Mass</h4>
                    <ul className="list-disc list-inside text-gray-400 space-y-1">
                        <li>Mass: 3.3011 × 10²³ kg</li>
                        <li>Radius: 2,439.7 km</li>
                        <li>Density: 5,427 kg/m³</li>
                        <li>Gravity: 3.7 m/s²</li>
                    </ul>
                </div>
                <div>
                    <h4 className="text-white font-medium mb-1">Temperature</h4>
                    <ul className="list-disc list-inside text-gray-400 space-y-1">
                        <li>Avg Surface: 167°C</li>
                        <li>Day: 430°C</li>
                        <li>Night: –180°C</li>
                    </ul>
                </div>
            </div>

            {/* Expandable Details */}
            <div>
                <button
                    onClick={() => setExpanded(!expanded)}
                    className="mt-4 text-blue-400 hover:text-blue-300 transition"
                >
                    {expanded ? '▲ Hide Details' : '▼ See More'}
                </button>

                {expanded && (
                    <div className="mt-4 space-y-4 text-sm text-gray-400">
                        <div>
                            <h4 className="text-white font-medium mb-1">Atmosphere</h4>
                            <ul className="list-disc list-inside">
                                <li>Very thin exosphere</li>
                                <li>Composed of oxygen, sodium, hydrogen, helium, potassium</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white font-medium mb-1">Surface Features</h4>
                            <ul className="list-disc list-inside">
                                <li>Heavily cratered like the Moon</li>
                                <li>Large impact basins (Caloris Basin)</li>
                                <li>Highlands and smooth plains</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white font-medium mb-1">Rotation & Orbit</h4>
                            <ul className="list-disc list-inside">
                                <li>Day Length: 58.6 Earth days</li>
                                <li>Year Length: 88 Earth days</li>
                                <li>Distance from Sun: ~57.9 million km</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white font-medium mb-1">Magnetic Field</h4>
                            <ul className="list-disc list-inside">
                                <li>Weak magnetic field</li>
                                <li>About 1% the strength of Earth's</li>
                                <li>Generated by partially liquid core</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white font-medium mb-1">Internal Structure</h4>
                            <ul className="list-disc list-inside">
                                <li>Large iron core (~85% of radius)</li>
                                <li>Thin silicate mantle and crust</li>
                                <li>Possible molten outer core</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-white font-medium mb-1">Exploration</h4>
                            <ul className="list-disc list-inside">
                                <li>Mariner 10: First flybys (1974–75)</li>
                                <li>MESSENGER: Orbited 2011–2015</li>
                                <li>BepiColombo: En route, arriving 2025</li>
                            </ul>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Mercury;
